### PR TITLE
Use colourblind-friendly colours in vignette

### PR DESCRIPTION
**Pull request by mblue9**
Wondering if you want to use colourblind-friendly colours in vignette where possible? Could be a good thing to do?

### CODE REVIEW

**Comment by stemangiola** [comment]
Sure why not, thanks!. Feel free to merge if it passes the tests.

**Comment by mblue9** [comment]
how do I (can I?) change the category colours in the heatmap (the 4 colours 1,2,3,4) to use the friendly colours?

**Comment by stemangiola** [comment]
> 
> 
> how do I (can I?) change the category colours in the heatmap (the 4 colours 1,2,3,4) to use the friendly colours?

palette_grouping = list(c("blue", "red", "#lkj234", ..))

**Comment by mblue9** [comment]
So if I try that e.g. below, the colours don't change. Am I missing something?

```
pbmc_small_cluster %>%
  join_transcripts(transcripts = marker_genes) %>% 
  group_by(label) %>% 
  heatmap(transcript, cell, abundance_counts, .scale = "column", 
                 palette_grouping = list(c("blue", "orange", "green", "yellow")))

**Comment by stemangiola** [comment]
> 
> 
> So if I try that e.g. below, the colours don't change. Am I missing something?
> 
> ```
> pbmc_small_cluster %>%
>   join_transcripts(transcripts = marker_genes) %>% 
>   group_by(label) %>% 
>   heatmap(transcript, cell, abundance_counts, .scale = "column", 
>                  palette_grouping = list(c("blue", "orange", "green", "yellow")))
> ```

probably a bug :(

**Comment by mblue9** [comment]
Ok no worries I won't worry about it here and will just merge the other changes. I can file an issue in tidyHeatmap to keep track if you like?

**Pull request merged**
