### PR TITLE
Few more vignette edits

### PR DESCRIPTION
**Pull request by mblue9**
- The plotly screenshot I added was quite large 3MB so compressed it here
- Removed `extract` from the Utilities table (thought it was a function you created but realised it was from tidyr)
- Few small edits to vignette
- Remove unused files (screenshots & logos)

### CODE REVIEW

**Comment by mblue9** [comment]
Just thought it's probably good to add a References section that has the refs for scran, scater, tidyHeatmap etc so I'll do that and add it here. Let me know if you want any more changes.

**Comment by mblue9** [comment]
Also realised I didn't update the README. Yeah keeping the vignette & README in sync is a bit of a pain but saw this and wonder if that could work https://www.garrickadenbuie.com/blog/dry-vignette-and-readme/. 

Basically you create a `man/fragments` with Rmd chunks and then can insert what you want into the vignette and README. Just one place to edit. I might try it if I can get the time sometime.

**Comment by stemangiola** [comment]
> 
> 
> Also realised I didn't update the README. Yeah keeping the vignette & README in sync is a bit of a pain but saw this and wonder if that could work https://www.garrickadenbuie.com/blog/dry-vignette-and-readme/.
> 
> Basically you create a `man/fragments` with Rmd chunks and then can insert what you want into the vignette and README. Just one place to edit. I might try it if I can get the time sometime.

That sound pretty awesome! (redundancy kills me, but as you aw in the post the most read is README, including me XD)

**Comment by mblue9** [comment]
>That sound pretty awesome! (redundancy kills me, but as you aw in the post the most read is README, including me XD)

Yep it wins... by 2% 😄 

Ok I might try that method then.

**Comment by stemangiola** [comment]
> Yep it wins... by 2% 😄

elections have been won for less than that!

**Review by stemangiola — COMMENTED** [review]
the images in man/figures have been deleted, but you said you recompiled the README, so they should be back. Am I missing something?

**Comment by mblue9** [comment]
That's what I meant, I need to recompile the README so far I'd just edited it.

**Comment by stemangiola** [comment]
> 
> 
> That's what I meant, I need to recompile the README so far I'd just edited it.

Cool, feel free to merge when you think is time.

**Comment by mblue9** [comment]
How did you get the plotly screenshot to show up in the README? If I have it as it was originally in your README 
`screenshot plotly`
That throws an error for me when I knit. `File "man/figures/plotly.png" not found in resource path` even though the image is there. So for the moment I've removed that line so the knit will work. But let me know if that's ok or how to add that image?

**Comment by mblue9** [comment]
Except for the plotly screenshot in the README this is ready for merge

**Pull request merged**
